url.pdf=https://integrador.bizlinks.com.pe/sfeperufiles/files/
!--url.pdf=http://testing.bizlinks.com.pe/sfeperufiles/files/
!--url.pdfh=http://172.19.64.84:9080/pdfgen-mod1-war/remoting/GeneracionPDF
url.pdfh=http://testing.bizlinks.com.pe/pdfgen-mod1-war/remoting/GeneracionPDF
!--url.pdfh2=http://172.19.64.84:9080/pdfgen-mod3-war/remoting/GeneracionPDF
url.pdfh2=http://testing.bizlinks.com.pe/pdfgen-mod3-war/remoting/GeneracionPDF
url.validate=http://ec2-54-244-165-155.us-west-2.compute.amazonaws.com:9084/validate